# Generated by Django 3.0.5 on 2020-05-16 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import epublisher.book.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('key', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('isbn', models.CharField(max_length=60, verbose_name='ISBN')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('publisher', models.CharField(max_length=200, verbose_name='Publisher')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ownership',
                'verbose_name_plural': 'Ownerships',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=epublisher.book.models.image_path)),
                ('epub', models.FileField(upload_to=epublisher.book.models.epub_path)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
    ]
